version: '3'
services:

  postgres:
    image: library/postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: library/redis:latest
    command: redis-server --requirepass pass-redis
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - 6379:6379

volumes:
  pgdata:
  redis:
